### ISSUE TITLE
论文复现验收

### ISSUE THREAD

**Issue by shiyutang** [kongdebug/SNUNet-Paddle#3]
前期训练同比之前结果较大，后续正常，但是依旧有波动：
<img width="933" alt="image" src="https://user-images.githubusercontent.com/34859558/164956198-8881a679-fe83-43ad-a164-5af28b16c14e.png">
![image](https://user-images.githubusercontent.com/34859558/164956234-01f07646-02d7-4511-a648-3af84ab0e4e2.png)

**Comment by kongdebug** [comment]
> 前期训练同比之前结果较大，后续正常，但是依旧有波动： <img alt="image" width="933" src="https://user-images.githubusercontent.com/34859558/164956198-8881a679-fe83-43ad-a164-5af28b16c14e.png"> ![image](https://user-images.githubusercontent.com/34859558/164956234-01f07646-02d7-4511-a648-3af84ab0e4e2.png)

这篇论文没有使用Normaliztion，所以一开始loss会比较大，训练5-10个epoch应该正常了。不好意思，忘记设置固定种子了…

**Comment by shiyutang** [comment]
训练到16个epoch正常：
<img width="925" alt="image" src="https://user-images.githubusercontent.com/34859558/164958791-04b7f23c-a23d-46a9-9217-287b6011acfc.png">

**Comment by kongdebug** [comment]
好的诗雨姐，感觉训练时候一开始读取数据的顺序也会影响。那验证和预测应该没问题吧

**Comment by shiyutang** [comment]
评估结果正常：
<img width="789" alt="image" src="https://user-images.githubusercontent.com/34859558/164959263-b5874d5a-75d1-4e50-9f14-a25223071330.png">

TIPC: 结果符合预期，时间正常。
<img width="784" alt="image" src="https://user-images.githubusercontent.com/34859558/164959218-ebff9014-7219-4df8-9c30-f5b559d688e9.png">
<img width="787" alt="image" src="https://user-images.githubusercontent.com/34859558/164959416-cbf3cd10-79c0-444a-967a-21ee63f6d360.png">
