### ISSUE TITLE
使用snunet_pred.py时Out of memory

### ISSUE THREAD

**Issue by zzhujiuxingc** [kongdebug/SNUNet-Paddle#4]
![Selection_001](https://user-images.githubusercontent.com/90132770/180918075-c2beec6e-0409-4aa1-9b55-a0d50c00d45f.png)

使用snunet_pred.py进行预测时内存太大，请问在哪里修改代码可以减少预测时使用的内存
如果想使用多卡进行预测，需要在哪里进行设置

**Comment by kongdebug** [comment]
1.爆显存是因为推理图像太大导致显存不足的，可以切块进行预测，得到结果之后又拼接回来成大图；另一种方法则是换显存更大的显卡。
2.本repo没有提供多卡预测的代码，一般是用多卡进行训练的，而且多卡预测应该也不能解决显存不足的问题；单机多卡预测可以建立多个predictor，每个predictor设置不同的gpu id

**Comment by kongdebug** [comment]
> ![Selection_001](https://user-images.githubusercontent.com/90132770/180918075-c2beec6e-0409-4aa1-9b55-a0d50c00d45f.png)
> 
> 使用snunet_pred.py进行预测时内存太大，请问在哪里修改代码可以减少预测时使用的内存 如果想使用多卡进行预测，需要在哪里进行设置

1.爆显存是因为推理图像太大导致显存不足的，可以切块进行预测，得到结果之后又拼接回来成大图；另一种方法则是换显存更大的显卡。
2.本repo没有提供多卡预测的代码，一般是用多卡进行训练的，而且多卡预测应该也不能解决显存不足的问题；单机多卡预测可以建立多个predictor，每个predictor设置不同的gpu id

**Comment by zzhujiuxingc** [comment]
> > ![Selection_001](https://user-images.githubusercontent.com/90132770/180918075-c2beec6e-0409-4aa1-9b55-a0d50c00d45f.png)
> > 使用snunet_pred.py进行预测时内存太大，请问在哪里修改代码可以减少预测时使用的内存 如果想使用多卡进行预测，需要在哪里进行设置
> 
> 1.爆显存是因为推理图像太大导致显存不足的，可以切块进行预测，得到结果之后又拼接回来成大图；另一种方法则是换显存更大的显卡。 2.本repo没有提供多卡预测的代码，一般是用多卡进行训练的，而且多卡预测应该也不能解决显存不足的问题；单机多卡预测可以建立多个predictor，每个predictor设置不同的gpu id

嗯 非常感谢 我在把图片换成256*256大小后可以顺利预测了
