### ISSUE TITLE
attention相关

### ISSUE THREAD

**Issue by lsyss-lsyss** [kongdebug/SNUNet-Paddle#6]
您好, 我在跑论文作者代码的时候遇到了一些问题, n = 8的时候, 使用ECAM注意力机制与不使用ECAM机制的话指标会有比较大的差距
----------------------------
不用ECAM:
![image](https://user-images.githubusercontent.com/57691843/188685418-b2fd85c8-b53b-4b4a-86eb-148e0d8eff4b.png)
-----------------------
用ECAM
![image](https://user-images.githubusercontent.com/57691843/188685417-7f721ede-2226-431e-b571-28b8c5cff3cf.png)
---------------------------
不使用ECAM的话指标反而更高
不知道您在复现的时候有没有遇到类似的问题, 谢谢

**Comment by kongdebug** [comment]
> ## 您好, 我在跑论文作者代码的时候遇到了一些问题, n = 8的时候, 使用ECAM注意力机制与不使用ECAM机制的话指标会有比较大的差距
> ## 不用ECAM:
> ![image](https://user-images.githubusercontent.com/57691843/188685418-b2fd85c8-b53b-4b4a-86eb-148e0d8eff4b.png)
> ## 用ECAM
> ![image](https://user-images.githubusercontent.com/57691843/188685417-7f721ede-2226-431e-b571-28b8c5cff3cf.png)
> 不使用ECAM的话指标反而更高 不知道您在复现的时候有没有遇到类似的问题, 谢谢

没有诶，没有不使用ECAM训练过，我只用paddle复现了模型，并按照论文给的参数进行了训练得到符合预期的结果，没有做其他消融实验等… 可能你需要仔细对照超参数，这差距确实有点大……可以直接向作者提问
